#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const force = process.argv.includes("--force");

const envPath = resolve(root, ".env");
const providersPath = resolve(root, "providers.json");
const providersExamplePath = resolve(root, "providers.example.json");

const generated = [];
const skipped = [];

if (existsSync(envPath) && !force) {
  skipped.push(".env (already exists - pass --force to regenerate)");
} else {
  const vaultKey = randomBytes(32).toString("base64");
  const hmacKey = randomBytes(32).toString("base64");
  const existing = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";
  const preserved = existing
    .split(/\r?\n/)
    .filter((line) => {
      const key = line.split("=")[0]?.trim();
      return key && !["VAULT_KEY", "SESSION_HMAC_KEY"].includes(key);
    })
    .join("\n");
  const banner = `# Generated by scripts/setup.mjs on ${new Date().toISOString()}`;
  const body = [
    banner,
    `VAULT_KEY=${vaultKey}`,
    `SESSION_HMAC_KEY=${hmacKey}`,
    preserved,
  ]
    .filter(Boolean)
    .join("\n");
  writeFileSync(envPath, `${body.trimEnd()}\n`, { mode: 0o600 });
  generated.push(".env (with fresh VAULT_KEY and SESSION_HMAC_KEY)");
}

if (existsSync(providersPath) && !force) {
  skipped.push("providers.json (already exists - pass --force to overwrite)");
} else if (!existsSync(providersExamplePath)) {
  console.error(
    "providers.example.json not found - cannot seed providers.json",
  );
  process.exit(1);
} else {
  copyFileSync(providersExamplePath, providersPath);
  generated.push("providers.json (copied from providers.example.json)");
}

console.log("legacy-proxy setup");
console.log("==================");
if (generated.length) {
  console.log("\nCreated:");
  for (const item of generated) console.log(`  + ${item}`);
}
if (skipped.length) {
  console.log("\nLeft alone:");
  for (const item of skipped) console.log(`  · ${item}`);
}
console.log("\nNext steps:");
console.log(
  "  1. Edit providers.json - set IMAP/SMTP hosts for your mailserver.",
);
console.log("  2. Start the proxy:  docker compose -f compose.prod.yml up -d");
console.log("  3. Open http://localhost:8080/.well-known/jmap to verify.\n");
